version: "3"

services:

  runtime-setup:
    image: swift-memcache-gsoc:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  test:
    image: swift-memcache-gsoc:22.04-5.9
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-memcache-gsoc:22.04-5.9

  update-benchmark-baseline:
    image: swift-memcache-gsoc:22.04-5.9
    environment:
      - SWIFT_VERSION=5.9
